#!/bin/bash

echo "=========================================="
echo "Supabase Configuration Helper"
echo "=========================================="
echo ""
echo "This script will help you configure Supabase redirect URLs."
echo ""
echo "STEP 1: Add Redirect URLs in Supabase Dashboard"
echo "------------------------------------------------"
echo "1. Go to: https://supabase.com/dashboard"
echo "2. Select project: ooaxtwmqrvfzdqzoijcj"
echo "3. Navigate to: Authentication → URL Configuration"
echo "4. Add these Redirect URLs:"
echo "   - http://localhost:32100/**"
echo "   - https://noticebazaar.com/**"
echo "   - https://*.vercel.app/** (if using Vercel)"
echo ""
echo "STEP 2: Set FRONTEND_URL Secret"
echo "--------------------------------"
echo "1. Go to: Edge Functions → Secrets"
echo "2. Add new secret:"
echo "   Name: FRONTEND_URL"
echo "   Value: https://noticebazaar.com"
echo ""
echo "STEP 3: Verify Site URL"
echo "----------------------"
echo "1. Go to: Authentication → URL Configuration"
echo "2. Ensure Site URL is: https://noticebazaar.com"
echo ""
echo "=========================================="
echo "Detailed instructions saved to: CONFIGURE_SUPABASE_REDIRECT.md"
echo "=========================================="
