module.exports = {
  source: 'dist',
  include: [
    '/',
    '/about',
    '/brands',
    '/brand-directory',
    '/pricing-comparison',
    '/free-legal-check',
    '/free-influencer-contract',
    '/collaboration-agreement-generator',
    '/barter-collab',
    '/patna-influencers',
    '/careers',
    '/blog',
  ],
  minifyHtml: {
    collapseWhitespace: false,
    removeComments: false,
  },
  skipThirdPartyRequests: true,
  cacheAjaxRequests: false,
  puppeteerArgs: ['--no-sandbox', '--disable-setuid-sandbox'],
  fixWebpackChunksIssue: false,
  removeStyleTags: false,
  removeScriptTags: false,
  waitFor: 3000,
  crawlFrom: '/',
  removeDataAttributes: false,
  inlineCss: false,
};
