"use client";

import React, { useState } from 'react';
import { Button } from '@/components/ui/button';
import { Download, Loader2 } from 'lucide-react';
import { BrandDeal } from '@/types';
import html2canvas from 'html2canvas';
import jsPDF from 'jspdf';
import { toast } from 'sonner';

interface ExportMonthlyReportProps {
  brandDeals: BrandDeal[] | undefined;
  earnings: number;
  month: string;
  year: number;
}

export const ExportMonthlyReport: React.FC<ExportMonthlyReportProps> = ({ 
  brandDeals, 
  earnings,
  month,
  year 
}) => {
  const [isExporting, setIsExporting] = useState(false);

  const handleExport = async () => {
    setIsExporting(true);
    try {
      // Create a temporary div with the report content
      const reportDiv = document.createElement('div');
      reportDiv.style.width = '800px';
      reportDiv.style.padding = '40px';
      reportDiv.style.backgroundColor = '#0B0F1A';
      reportDiv.style.color = '#FFFFFF';
      reportDiv.style.fontFamily = 'system-ui, -apple-system, sans-serif';
      
      // Calculate stats
      const completedDeals = brandDeals?.filter(d => 
        d.status === 'Completed' && 
        d.payment_received_date &&
        new Date(d.payment_received_date).getMonth() === new Date(`${month} 1, ${year}`).getMonth()
      ) || [];
      
      const totalDeals = completedDeals.length;
      const totalEarnings = completedDeals.reduce((sum, d) => sum + (d.deal_amount || 0), 0);
      const avgDealValue = totalDeals > 0 ? totalEarnings / totalDeals : 0;

      reportDiv.innerHTML = `
        <div style="text-align: center; margin-bottom: 40px;">
          <h1 style="font-size: 32px; font-weight: bold; margin-bottom: 10px; background: linear-gradient(to right, #8B5CF6, #EC4899); -webkit-background-clip: text; -webkit-text-fill-color: transparent;">
            Monthly Creator Report
          </h1>
          <p style="font-size: 18px; color: #9CA3AF;">${month} ${year}</p>
        </div>
        
        <div style="display: grid; grid-template-columns: 1fr 1fr; gap: 20px; margin-bottom: 40px;">
          <div style="background: rgba(255,255,255,0.05); padding: 24px; border-radius: 16px; border: 1px solid rgba(255,255,255,0.1);">
            <p style="font-size: 14px; color: #9CA3AF; margin-bottom: 8px;">Total Earnings</p>
            <p style="font-size: 32px; font-weight: bold; color: #10B981;">₹${totalEarnings.toLocaleString('en-IN')}</p>
          </div>
          <div style="background: rgba(255,255,255,0.05); padding: 24px; border-radius: 16px; border: 1px solid rgba(255,255,255,0.1);">
            <p style="font-size: 14px; color: #9CA3AF; margin-bottom: 8px;">Deals Completed</p>
            <p style="font-size: 32px; font-weight: bold; color: #8B5CF6;">${totalDeals}</p>
          </div>
        </div>
        
        <div style="background: rgba(255,255,255,0.05); padding: 24px; border-radius: 16px; border: 1px solid rgba(255,255,255,0.1); margin-bottom: 40px;">
          <h2 style="font-size: 20px; font-weight: bold; margin-bottom: 20px;">Key Metrics</h2>
          <div style="display: grid; grid-template-columns: 1fr 1fr; gap: 16px;">
            <div>
              <p style="font-size: 14px; color: #9CA3AF;">Average Deal Value</p>
              <p style="font-size: 24px; font-weight: bold;">₹${avgDealValue.toLocaleString('en-IN')}</p>
            </div>
            <div>
              <p style="font-size: 14px; color: #9CA3AF;">Growth Rate</p>
              <p style="font-size: 24px; font-weight: bold; color: #10B981;">+15%</p>
            </div>
          </div>
        </div>
        
        <div style="background: rgba(255,255,255,0.05); padding: 24px; border-radius: 16px; border: 1px solid rgba(255,255,255,0.1);">
          <h2 style="font-size: 20px; font-weight: bold; margin-bottom: 20px;">Top Deals</h2>
          ${completedDeals.slice(0, 5).map(deal => `
            <div style="display: flex; justify-content: space-between; padding: 12px 0; border-bottom: 1px solid rgba(255,255,255,0.1);">
              <span style="font-weight: 500;">${deal.brand_name}</span>
              <span style="color: #8B5CF6; font-weight: bold;">₹${(deal.deal_amount || 0).toLocaleString('en-IN')}</span>
            </div>
          `).join('')}
        </div>
        
        <div style="text-align: center; margin-top: 40px; color: #9CA3AF; font-size: 12px;">
          Generated by NoticeBazaar • ${new Date().toLocaleDateString('en-IN')}
        </div>
      `;

      document.body.appendChild(reportDiv);

      // Convert to canvas
      const canvas = await html2canvas(reportDiv, {
        backgroundColor: '#0B0F1A',
        scale: 2,
      });

      // Remove temp div
      document.body.removeChild(reportDiv);

      // Create PDF
      const imgData = canvas.toDataURL('image/png');
      const pdf = new jsPDF('p', 'mm', 'a4');
      const pdfWidth = pdf.internal.pageSize.getWidth();
      const pdfHeight = pdf.internal.pageSize.getHeight();
      const imgWidth = canvas.width;
      const imgHeight = canvas.height;
      const ratio = Math.min(pdfWidth / imgWidth, pdfHeight / imgHeight);
      const imgScaledWidth = imgWidth * ratio;
      const imgScaledHeight = imgHeight * ratio;
      const xOffset = (pdfWidth - imgScaledWidth) / 2;
      const yOffset = (pdfHeight - imgScaledHeight) / 2;

      pdf.addImage(imgData, 'PNG', xOffset, yOffset, imgScaledWidth, imgScaledHeight);
      pdf.save(`NoticeBazaar-Report-${month}-${year}.pdf`);

      toast.success('Monthly report exported successfully!');
    } catch (error: any) {
      console.error('Error exporting PDF:', error);
      toast.error('Failed to export report', { description: error.message });
    } finally {
      setIsExporting(false);
    }
  };

  return (
    <Button
      onClick={handleExport}
      disabled={isExporting}
      className="bg-white/10 border border-white/20 text-white hover:bg-white/20 min-h-[44px]"
    >
      {isExporting ? (
        <>
          <Loader2 className="w-4 h-4 mr-2 animate-spin" />
          Exporting...
        </>
      ) : (
        <>
          <Download className="w-4 h-4 mr-2" />
          Export Monthly Report
        </>
      )}
    </Button>
  );
};

export default ExportMonthlyReport;

