export const CITY_OPTIONS = [
  'Mumbai', 'Delhi', 'New Delhi', 'Bengaluru', 'Hyderabad', 'Chennai', 'Kolkata', 'Pune', 'Ahmedabad', 'Jaipur',
  'Surat', 'Lucknow', 'Kanpur', 'Nagpur', 'Indore', 'Thane', 'Bhopal', 'Visakhapatnam', 'Patna', 'Vadodara',
  'Ghaziabad', 'Ludhiana', 'Agra', 'Nashik', 'Faridabad', 'Meerut', 'Rajkot', 'Varanasi', 'Srinagar', 'Amritsar',
  'Noida', 'Gurugram', 'Chandigarh', 'Greater Noida', 'Kochi', 'Coimbatore', 'Mysuru', 'Navi Mumbai', 'Aurangabad',
  'Solapur', 'Kolhapur', 'Sangli', 'Satara', 'Jalgaon', 'Akola', 'Amravati', 'Nanded', 'Ujjain', 'Gwalior',
  'Jhansi', 'Gorakhpur', 'Lucknow', 'Meerut', 'Prayagraj', 'Varanasi', 'Aligarh', 'Bareilly', 'Moradabad',
  'Saharanpur', 'Dehradun', 'Haridwar', 'Rishikesh', 'Haldwani', 'Roorkee', 'Shimla', 'Solan', 'Dharamshala',
  'Mandi', 'Hamirpur', 'Bilaspur', 'Kullu', 'Chamba', 'Una', 'Jammu', 'Leh', 'Kathua', 'Udhampur', 'Srinagar',
  'Anantnag', 'Baramulla', 'Sopore', 'Ganderbal', 'Pulwama', 'Shopian', 'Kulgam', 'Bandipora', 'Kupwara',
  'Budgam', 'Poonch', 'Rajouri', 'Reasi', 'Ramban', 'Kishtwar', 'Doda', 'Samba', 'Leh', 'Kargil',
  'Raipur', 'Bhilai', 'Bilaspur', 'Korba', 'Durg', 'Rajnandgaon', 'Jagdalpur', 'Ambikapur', 'Dhamtari', 'Raigarh',
  'Ranchi', 'Jamshedpur', 'Dhanbad', 'Bokaro', 'Deoghar', 'Phusro', 'Hazaribagh', 'Giridih', 'Ramgarh', 'Medininagar',
  'Bhubaneswar', 'Cuttack', 'Rourkela', 'Berhampur', 'Sambalpur', 'Puri', 'Balasore', 'Bhadrak', 'Baripada', 'Jharsuguda',
  'Guwahati', 'Silchar', 'Dibrugarh', 'Jorhat', 'Nagaon', 'Tinsukia', 'Tezpur', 'Bongaigaon', 'Dhubri', 'Diphu',
  'Agartala', 'Shillong', 'Aizawl', 'Imphal', 'Kohima', 'Itanagar', 'Gangtok', 'Port Blair', 'Kavaratti',
  'Panaji', 'Vasco da Gama', 'Margao', 'Mapusa', 'Ponda', 'Bicholim', 'Curchorem', 'Quepem', 'Canacona', 'Cuncolim',
  'Ludhiana', 'Amritsar', 'Jalandhar', 'Patiala', 'Bathinda', 'Mohali', 'Hoshiarpur', 'Pathankot', 'Moga', 'Abohar',
  'Phagwara', 'Khanna', 'Muktsar', 'Barnala', 'Rajpura', 'Firozpur', 'Kapurthala', 'Sangrur', 'Batala', 'Malerkotla',
  'Bathinda', 'Jalandhar', 'Patiala', 'Mohali', 'Pathankot', 'Hoshiarpur', 'Moga', 'Phagwara', 'Hubballi', 'Belagavi',
  'Kalaburagi', 'Mangaluru', 'Davanagere', 'Ballari', 'Shivamogga', 'Tumakuru', 'Udupi', 'Hassan', 'Vijayawada',
  'Guntur', 'Nellore', 'Kurnool', 'Rajahmundry', 'Tirupati', 'Kadapa', 'Eluru', 'Kakinada', 'Warangal', 'Karimnagar',
  'Nizamabad', 'Khammam', 'Mahbubnagar', 'Karur', 'Madurai', 'Tiruchirappalli', 'Salem', 'Erode', 'Vellore',
  'Thoothukudi', 'Nagercoil', 'Dindigul', 'Thanjavur', 'Tirunelveli', 'Thrissur', 'Kannur', 'Kozhikode', 'Alappuzha',
  'Kottayam', 'Palakkad', 'Malappuram', 'Kollam'
];
