import { supabase } from '../index.js';

export interface DealDetailsToken {
  id: string;
  creator_id: string;
  is_active: boolean;
  expires_at: string | null;
  revoked_at: string | null;
  used_at: string | null; // Timestamp when brand submitted (locks form)
  created_at: string;
  updated_at: string;
}

export interface CreateDealDetailsTokenOptions {
  creatorId: string;
  expiresAt?: Date | null;
}

/**
 * Create a secure deal details token
 * @param options Token creation options
 * @returns The created token
 */
export async function createDealDetailsToken(
  options: CreateDealDetailsTokenOptions
): Promise<DealDetailsToken> {
  const { creatorId, expiresAt } = options;

  // Validate inputs
  if (!creatorId) {
    throw new Error('creatorId is required');
  }

  // Create token (UUID v4 is generated by database default)
  const { data: token, error: tokenError } = await supabase
    .from('deal_details_tokens')
    .insert({
      creator_id: creatorId,
      expires_at: expiresAt ? expiresAt.toISOString() : null,
      is_active: true,
    })
    .select()
    .single();

  if (tokenError || !token) {
    console.error('[DealDetailsTokenService] Token creation error:', tokenError);
    throw new Error('Failed to create deal details token');
  }

  return token;
}

/**
 * Get token info (public access for form page)
 * @param tokenId Token ID
 * @returns Token info with creator name
 */
export async function getDealDetailsTokenInfo(tokenId: string): Promise<{
  token: DealDetailsToken;
  creatorName: string;
} | null> {
  // Validate token format (UUID v4)
  const uuidRegex = /^[0-9a-f]{8}-[0-9a-f]{4}-4[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i;
  if (!uuidRegex.test(tokenId.trim())) {
    return null;
  }

  // Fetch token with creator info
  const { data: tokenData, error: tokenError } = await supabase
    .from('deal_details_tokens')
    .select(`
      *,
      profiles:creator_id (
        first_name,
        last_name
      )
    `)
    .eq('id', tokenId.trim())
    .maybeSingle();

  if (tokenError || !tokenData) {
    return null;
  }

  // Check if token is active
  if (!tokenData.is_active || tokenData.revoked_at) {
    return null;
  }

  // Check if token is expired
  if (tokenData.expires_at) {
    const expiresAt = new Date(tokenData.expires_at);
    if (expiresAt < new Date()) {
      return null;
    }
  }

  // Note: We still return token info even if used_at is set (for read-only view)

  // Extract creator name
  const profile = tokenData.profiles as any;
  const creatorName = profile
    ? `${profile.first_name || ''} ${profile.last_name || ''}`.trim() || 'the creator'
    : 'the creator';

  return {
    token: tokenData as DealDetailsToken,
    creatorName,
  };
}

/**
 * Submit deal details form
 * @param tokenId Token ID
 * @param formData Form submission data
 * @returns Created deal ID (if deal was created)
 */
export async function submitDealDetails(
  tokenId: string,
  formData: any
): Promise<{ submissionId: string; dealId: string | null }> {
  // Validate token
  const tokenInfo = await getDealDetailsTokenInfo(tokenId);
  if (!tokenInfo) {
    throw new Error('Invalid or expired token');
  }

  const { token } = tokenInfo;

  // Check if token has already been used (immutability)
  if (token.used_at) {
    throw new Error('This form has already been submitted and cannot be edited. Please contact the creator for changes.');
  }

  // Mark token as used (lock the form)
  const { error: updateError } = await supabase
    .from('deal_details_tokens')
    .update({ used_at: new Date().toISOString() })
    .eq('id', tokenId);

  if (updateError) {
    console.error('[DealDetailsTokenService] Token update error:', updateError);
    // Continue anyway - submission is more important
  }

  // Create submission
  const { data: submission, error: submissionError } = await supabase
    .from('deal_details_submissions')
    .insert({
      token_id: tokenId,
      creator_id: token.creator_id,
      form_data: formData,
    })
    .select()
    .single();

  if (submissionError || !submission) {
    console.error('[DealDetailsTokenService] Submission error:', submissionError);
    throw new Error('Failed to submit deal details');
  }

  // Create draft deal from form data
  let dealId: string | null = null;
  try {
    const dealData: any = {
      creator_id: token.creator_id,
      brand_name: formData.brandName || 'Brand',
      deal_amount: formData.dealType === 'paid' && formData.paymentAmount
        ? parseFloat(formData.paymentAmount) || 0
        : 0,
      deliverables: JSON.stringify(formData.deliverables || []),
      due_date: formData.deadline || new Date().toISOString().split('T')[0],
      payment_expected_date: formData.deadline || new Date().toISOString().split('T')[0],
      status: 'Brand_Details_Submitted', // Special status for creator review
      platform: 'Other',
      deal_type: formData.dealType || 'paid',
      created_via: 'deal_details_form',
      // Save brand address from company address (fetched via GST lookup)
      brand_address: formData.companyAddress || null,
      brand_email: formData.companyEmail || null,
    };

    const { data: deal, error: dealError } = await supabase
      .from('brand_deals')
      .insert(dealData)
      .select()
      .single();

    if (!dealError && deal) {
      dealId = deal.id;

      // Update submission with deal_id
      await supabase
        .from('deal_details_submissions')
        .update({ deal_id: deal.id })
        .eq('id', submission.id);
    } else if (dealError) {
      console.error('[DealDetailsTokenService] Deal creation error:', dealError);
      // If deal creation failed, try to update existing deal if deal_id exists in submission
      if (submission.deal_id) {
        console.log('[DealDetailsTokenService] Attempting to update existing deal with brand address');
        const { error: updateError } = await supabase
          .from('brand_deals')
          .update({
            brand_address: formData.companyAddress || null,
            brand_email: formData.companyEmail || null,
          })
          .eq('id', submission.deal_id);
        
        if (updateError) {
          console.error('[DealDetailsTokenService] Deal update error:', updateError);
        } else {
          console.log('[DealDetailsTokenService] Successfully updated existing deal with brand address');
          dealId = submission.deal_id;
        }
      }
    }
  } catch (error) {
    console.error('[DealDetailsTokenService] Deal creation error:', error);
    // Don't fail the submission if deal creation fails
  }

  return {
    submissionId: submission.id,
    dealId,
  };
}

/**
 * Get submitted deal details for a deal (creator access)
 * @param dealId Deal ID
 * @returns Submission data if exists
 */
export async function getDealSubmissionDetails(dealId: string): Promise<{
  submission: any;
  formData: any;
} | null> {
  const { data: submission, error } = await supabase
    .from('deal_details_submissions')
    .select('*, deal_details_tokens!inner(*)')
    .eq('deal_id', dealId)
    .maybeSingle();

  if (error || !submission) {
    return null;
  }

  return {
    submission,
    formData: submission.form_data,
  };
}

