import { createClient } from '@supabase/supabase-js';
import * as dotenv from 'dotenv';
import path from 'path';
import fs from 'fs';
import axios from 'axios';
import { execSync } from 'child_process';

dotenv.config({ path: path.resolve(process.cwd(), '.env') });
dotenv.config({ path: path.resolve(process.cwd(), '.env.local') });

const supabaseUrl = process.env.VITE_SUPABASE_URL;
const supabaseKey = process.env.SUPABASE_SERVICE_ROLE_KEY || process.env.VITE_SUPABASE_ANON_KEY;

if (!supabaseUrl || !supabaseKey) {
  console.error('❌ Error: Missing Supabase credentials');
  process.exit(1);
}

const supabase = createClient(supabaseUrl, supabaseKey);

// Target creators with videos > 6 MB
const creatorsToOptimize = [
  { username: '_cookingwithvineet', originalSize: '25.36 MB' },
  { username: '_small_home_kitchen', originalSize: '24.83 MB' },
  { username: 'shinyyy.05', originalSize: '21.85 MB' },
  { username: 'littleexplorermommy', originalSize: '17.81 MB' },
  { username: 'krishnavi_healthy_bites', originalSize: '16.58 MB' },
  { username: 'monika.urs', originalSize: '16.38 MB' },
  { username: 'myspace_vlogs', originalSize: '14.87 MB' },
  { username: 'chroniclesofffoods', originalSize: '12.64 MB' },
  { username: 'thegurgaonfoodie', originalSize: '12.44 MB' },
  { username: 'homechef_duggu', originalSize: '12.27 MB' },
  { username: 'cookku_with_chikku', originalSize: '10.50 MB' }
];

async function downloadFile(url: string, dest: string): Promise<void> {
  const writer = fs.createWriteStream(dest);
  const response = await axios({
    url,
    method: 'GET',
    responseType: 'stream',
  });
  response.data.pipe(writer);
  return new Promise((resolve, reject) => {
    writer.on('finish', resolve);
    writer.on('error', reject);
  });
}

async function compressAndOptimize() {
  console.log(`🚀 Starting platform-wide batch compression for ${creatorsToOptimize.length} bulky creators...`);
  
  // Ensure temp dir exists
  const tempDir = path.join(process.cwd(), 'temp_reels');
  if (!fs.existsSync(tempDir)) {
    fs.mkdirSync(tempDir);
  }

  for (const creator of creatorsToOptimize) {
    console.log(`\n----------------------------------------`);
    console.log(`👤 Processing Creator: @${creator.username} (Original: ${creator.originalSize})`);

    try {
      // 1. Fetch current profile to get video URL
      const { data: profile, error: fetchError } = await supabase
        .from('profiles')
        .select('discovery_video_url')
        .eq('username', creator.username)
        .single();

      if (fetchError || !profile || !profile.discovery_video_url) {
        console.warn(`⚠️ Skipped: Could not fetch video URL for @${creator.username}`);
        continue;
      }

      const inputUrl = profile.discovery_video_url;
      const originalPath = path.join(tempDir, `${creator.username}_original.mp4`);
      const optimizedPath = path.join(tempDir, `${creator.username}_optimized.mp4`);

      // 2. Download original file
      console.log(`📥 Downloading original video...`);
      await downloadFile(inputUrl, originalPath);

      // 3. Compress using FFmpeg
      console.log(`🎬 Transcoding to H.264 / FastStart (480x854, 600 kbps max)...`);
      const ffmpegCmd = `ffmpeg -y -i "${originalPath}" -vf "scale=480:854" -c:v libx264 -preset fast -crf 28 -maxrate 600k -bufsize 1200k -pix_fmt yuv420p -movflags +faststart -c:a aac -b:a 64k "${optimizedPath}"`;
      
      execSync(ffmpegCmd, { stdio: 'ignore' });

      // Verify optimized file exists and check size
      if (!fs.existsSync(optimizedPath)) {
        throw new Error('Optimized file was not generated by FFmpeg');
      }
      
      const stats = fs.statSync(optimizedPath);
      const newSizeMB = (stats.size / (1024 * 1024)).toFixed(2);
      console.log(`✅ Transcoding complete. New Size: ${newSizeMB} MB`);

      // 4. Upload to Supabase Storage
      const storagePath = `discovery-reels/${creator.username}-optimized.mp4`;
      console.log(`📤 Uploading optimized video to creator-discovery storage...`);
      
      const fileBuffer = fs.readFileSync(optimizedPath);
      const { error: uploadError } = await supabase.storage
        .from('creator-discovery')
        .upload(storagePath, fileBuffer, {
          contentType: 'video/mp4',
          upsert: true
        });

      if (uploadError) throw uploadError;

      // 5. Get Public URL & update profile in database
      const { data: { publicUrl } } = supabase.storage
        .from('creator-discovery')
        .getPublicUrl(storagePath);

      const { error: updateError } = await supabase
        .from('profiles')
        .update({ discovery_video_url: publicUrl })
        .eq('username', creator.username);

      if (updateError) throw updateError;
      console.log(`✨ Success! Updated database for @${creator.username} to new URL.`);

      // Clean up local temp files
      try {
        fs.unlinkSync(originalPath);
        fs.unlinkSync(optimizedPath);
      } catch (err) {}

    } catch (err: any) {
      console.error(`❌ Failed to process @${creator.username}:`, err.message);
    }
  }

  // Remove temp directory
  try {
    fs.rmdirSync(tempDir);
  } catch (err) {}

  console.log(`\n========================================`);
  console.log(`🎉 Batch Compression Completed successfully!`);
}

compressAndOptimize();
