-- Add Shagufi Khan (shagufikhan_) to profiles
INSERT INTO public.profiles (
    id,
    username,
    instagram_handle,
    first_name,
    role,
    bio,
    location,
    followers_count,
    engagement_rate,
    is_verified,
    is_elite_verified,
    starting_price,
    reel_price,
    avg_rate_reel,
    barter_min_value,
    onboarding_complete,
    open_to_collabs,
    content_niches,
    creator_category,
    audience_gender_split,
    audience_age_range,
    top_cities,
    avg_reel_views_manual,
    past_brand_count,
    past_brands,
    reliability_score,
    response_hours
)
VALUES (
    gen_random_uuid(), -- Temporary until linked with auth
    'shagufikhan_',
    'shagufikhan_',
    'Shagufi Khan',
    'creator',
    '✨ Ambitious dreamer with creative sparkles | Makeup 💄 Fashion 👗 Lifestyle 🏠. High interaction | Strong hooks.',
    'Delhi, India',
    139600,
    6.7,
    true,
    true,
    5000,
    8000,
    8000,
    4000,
    true,
    true,
    ARRAY['Fashion', 'Lifestyle', 'Beauty'],
    'Fashion',
    '20% Women, 80% Men',
    '18-24',
    ARRAY['Delhi, India'],
    70600,
    15,
    ARRAY['AURIC', 'Velura'],
    99,
    2
)
ON CONFLICT (instagram_handle) DO UPDATE SET
    reel_price = 8000,
    avg_rate_reel = 8000,
    followers_count = 139600,
    engagement_rate = 6.7,
    audience_gender_split = '20% Women, 80% Men',
    onboarding_complete = true;
